#!/usr/bin/env python3
"""Statistical verification that unknown-episode counts are Poisson.

Three tests (results appended to poisson_proof.md by this script):
  A. Replication experiment: R independent runs over the SAME built layers
     (construction seeds fixed; only the run-time seeds vary), each D miles.
     Under the Poisson hypothesis the counts N_1..N_R are iid Poisson(lam).
     -> dispersion test ((R-1)*Var/Mean ~ chi2_{R-1}) and chi-square GOF
        against Poisson(mean).
  B. Window counts of the delivered 2M-mile run (200 disjoint windows):
     -> dispersion test against chi2_{W-1}.
  C. Inter-arrival distances of the delivered run vs the exponential
     distribution (KS test) - exponential gaps <=> Poisson process.

Also writes poisson_proof.png (histograms vs Poisson PMF, QQ plot).
"""

import csv
import json
import math

import numpy as np
from scipy import stats
import matplotlib
matplotlib.use("Agg")
import matplotlib.pyplot as plt

from simulator import ScenarioSimulator, SimConfig

R_RUNS = 300
RUN_MILES = 3000.0


def dispersion_test(counts):
    counts = np.asarray(counts, dtype=float)
    n = len(counts)
    mean = counts.mean()
    var = counts.var(ddof=1)
    d = var / mean
    stat = (n - 1) * d                      # ~ chi2_{n-1} under Poisson
    p_lo = stats.chi2.cdf(stat, n - 1)
    p = 2 * min(p_lo, 1 - p_lo)             # two-sided
    return mean, var, d, stat, p


def poisson_gof(counts):
    """Chi-square goodness of fit against Poisson(mean), bins merged to
    expected count >= 5."""
    counts = np.asarray(counts)
    lam = counts.mean()
    n = len(counts)
    kmax = int(counts.max()) + 1
    obs = np.bincount(counts.astype(int), minlength=kmax + 1).astype(float)
    exp = np.array([stats.poisson.pmf(k, lam) * n for k in range(kmax)] +
                   [stats.poisson.sf(kmax - 1, lam) * n])
    # merge adjacent bins until every expected count >= 5
    ob, ex = [], []
    co = ce = 0.0
    for o, e in zip(obs, exp):
        co += o; ce += e
        if ce >= 5:
            ob.append(co); ex.append(ce); co = ce = 0.0
    if ce > 0 or co > 0:
        if ex:
            ob[-1] += co; ex[-1] += ce
        else:
            ob, ex = [co], [ce]
    ob, ex = np.array(ob), np.array(ex)
    ex *= ob.sum() / ex.sum()
    stat = ((ob - ex) ** 2 / ex).sum()
    dof = len(ob) - 1 - 1                   # -1 for estimated lambda
    p = stats.chi2.sf(stat, max(dof, 1))
    return lam, stat, max(dof, 1), p, (ob, ex)


def main():
    cfg = SimConfig.from_yaml("config.yaml")

    # ---------- A: replications over identical layers ----------
    base = dict(cfg.seeds)
    rep_counts = []
    for r in range(R_RUNS):
        seeds = dict(base)
        # construction streams fixed -> identical layers every run;
        # run-time streams varied -> independent realizations
        seeds["duration"] = 900_000 + r
        seeds["initial_state"] = 910_000 + r
        seeds["transition_sampling"] = 920_000 + r
        c = SimConfig.from_dict({**_raw_cfg(), "seeds": seeds,
                                 "target_total_miles": RUN_MILES})
        res = ScenarioSimulator(c).run()
        rep_counts.append(len(res.episodes))
    rep_counts = np.array(rep_counts)
    a_mean, a_var, a_d, a_stat, a_p = dispersion_test(rep_counts)
    a_lam, a_gstat, a_dof, a_gp, (a_ob, a_ex) = poisson_gof(rep_counts)

    # ---------- B: window counts of the delivered run ----------
    win = []
    with open("results/windows.csv", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            win.append(int(row["episode_start_count"]))
    b_mean, b_var, b_d, b_stat, b_p = dispersion_test(win)

    # ---------- C: inter-arrival distances vs exponential ----------
    inter = []
    with open("results/episodes.csv", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            inter.append(float(row["inter_arrival_miles"]))
    inter = np.array(inter)
    ks_stat, ks_p = stats.kstest(inter, "expon", args=(0, inter.mean()))

    # ---------- report ----------
    out = []
    out.append("\n## Empirical verification (generated by poisson_tests.py)\n")
    out.append(f"**A. Replication experiment.** {R_RUNS} independent runs of "
               f"{RUN_MILES:,.0f} miles over the *same* built layers "
               "(construction seeds fixed, run-time seeds varied). Under the "
               "Poisson hypothesis the run counts are iid Poisson.")
    out.append(f"- counts: mean {a_mean:.2f}, variance {a_var:.2f}, "
               f"dispersion {a_d:.3f}; dispersion test "
               f"(R-1)·D = {a_stat:.1f} vs chi2_{{{R_RUNS - 1}}} -> "
               f"p = {a_p:.3f}")
    out.append(f"- chi-square GOF vs Poisson({a_lam:.1f}): stat {a_gstat:.1f} "
               f"on {a_dof} dof -> p = {a_gp:.3f}")
    out.append(f"\n**B. Window counts of the 2M-mile run** (200 disjoint "
               "10,000-mile windows):")
    out.append(f"- mean {b_mean:.2f}, variance {b_var:.2f}, dispersion "
               f"{b_d:.3f}; test statistic {b_stat:.1f} vs chi2_199 -> "
               f"p = {b_p:.3f}")
    out.append(f"\n**C. Inter-arrival distances of the 2M-mile run** "
               f"(n = {len(inter):,}) vs Exponential(mean "
               f"{inter.mean():.2f} mi): KS statistic {ks_stat:.5f} -> "
               f"p = {ks_p:.3f} (exponential gaps <=> Poisson process)")
    verdict = (a_p > 0.05 and a_gp > 0.05 and b_p > 0.05 and ks_p > 0.05)
    out.append(f"\n**Verdict:** all tests {'PASS' if verdict else 'FAIL'} at "
               "the 5% level - the episode counts are statistically "
               "indistinguishable from Poisson, exactly as the theory "
               "predicts for p ~= 0.004.")
    with open("poisson_proof.md", "a", encoding="utf-8") as f:
        f.write("\n".join(out) + "\n")

    # ---------- plot ----------
    fig, axes = plt.subplots(1, 3, figsize=(15, 4.6))
    ax = axes[0]
    ks = np.arange(rep_counts.min() - 1, rep_counts.max() + 2)
    ax.hist(rep_counts, bins=np.arange(rep_counts.min() - 0.5,
                                       rep_counts.max() + 1.5),
            density=True, alpha=0.7, color="tab:blue",
            label=f"{R_RUNS} run counts")
    ax.plot(ks, stats.poisson.pmf(ks, a_lam), "ro-", ms=3, lw=1,
            label=f"Poisson({a_lam:.1f}) PMF")
    ax.set_title(f"A: counts of {R_RUNS} independent {RUN_MILES:,.0f}-mile "
                 f"runs\ndispersion {a_d:.3f} (p={a_p:.2f}), "
                 f"GOF p={a_gp:.2f}")
    ax.set_xlabel("episodes per run")
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3)

    ax = axes[1]
    wmin, wmax = min(win), max(win)
    ks2 = np.arange(wmin - 1, wmax + 2)
    ax.hist(win, bins=15, density=True, alpha=0.7, color="tab:blue",
            label="200 window counts")
    ax.plot(ks2, stats.poisson.pmf(ks2, np.mean(win)), "r-", lw=1.5,
            label=f"Poisson({np.mean(win):.1f}) PMF")
    ax.set_title(f"B: episode starts per 10,000-mile window\n"
                 f"dispersion {b_d:.3f} (p={b_p:.2f})")
    ax.set_xlabel("episode starts per window")
    ax.legend(fontsize=8)
    ax.grid(alpha=0.3)

    ax = axes[2]
    q = (np.arange(1, len(inter) + 1) - 0.5) / len(inter)
    theo = stats.expon.ppf(q, scale=inter.mean())
    ax.plot(theo, np.sort(inter), ".", ms=1, alpha=0.5)
    lim = max(theo.max(), inter.max())
    ax.plot([0, lim], [0, lim], "r--", lw=1)
    ax.set_title(f"C: QQ inter-arrival distances vs exponential\n"
                 f"KS p = {ks_p:.2f}")
    ax.set_xlabel("theoretical exponential quantiles (mi)")
    ax.set_ylabel("observed quantiles (mi)")
    ax.grid(alpha=0.3)
    fig.tight_layout()
    fig.savefig("poisson_proof.png", dpi=150)

    print(f"A: mean {a_mean:.2f} var {a_var:.2f} D {a_d:.3f} p {a_p:.3f} | "
          f"GOF p {a_gp:.3f}")
    print(f"B: D {b_d:.3f} p {b_p:.3f}")
    print(f"C: KS {ks_stat:.5f} p {ks_p:.3f}")
    print("verdict:", "PASS" if verdict else "FAIL")


def _raw_cfg():
    import yaml
    with open("config.yaml", encoding="utf-8") as f:
        return yaml.safe_load(f)


if __name__ == "__main__":
    main()
